apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegram-demo
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: telegram-bot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
secretGenerator:
  - name: bot-secrets
    envs:
      - secret.env